### PR TITLE
[WIP] Test false positive causal cell race

### PR DESCRIPTION
**Pull request by phlip9**
see issue #37

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks :+1: my best guess here is `thread::spawn` is not bumping the causality version vector. If you want to take a look, see how other points of concurrency bump the version vec and you can probably attempt a fix.

This is the field: https://github.com/carllerche/loom/blob/master/src/rt/thread.rs#L21

**Comment by carllerche** [comment]
Thanks :+1: I pushed a fix to the branch. I would appreciate any further tests you may write :)

**Comment by phlip9** [comment]
Ah great! I just found this issue, but it looks like you fixed it first :)
I'll close the issue as well.

**Comment by carllerche** [comment]
Ah, sorry about that. I ended up doing a context switch to loom last
night to merge a bunch of other PRs too...

**Pull request merged**
